"""Add link_externo and other fields to Material

Revision ID: 4617117b9b96
Revises: 41e37b6f8b2a
Create Date: 2025-11-26 00:27:39.041143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4617117b9b96'
down_revision = '41e37b6f8b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_externo', sa.String(length=500), nullable=True))
        batch_op.alter_column('arquivo_path',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.alter_column('arquivo_path',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.drop_column('link_externo')

    # ### end Alembic commands ###
